# Colors
COLOR_WHITE = (255,255,255)
COLOR_BLACK = (0,0,0)

# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_COLOR = COLOR_BLACK

# Asteroid
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
